# Generated by Django 2.0.7 on 2018-08-12 12:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20180812_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
