# Generated by Django 2.0.7 on 2018-08-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='address',
            new_name='account_id',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='secretKey',
            new_name='master_seed',
        ),
        migrations.AddField(
            model_name='wallet',
            name='master_seed_hex',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='public_key',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='public_key_hex',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
